# TCL File Generated by Component Editor 21.1
# Thu Dec 08 19:52:21 GST 2022
# DO NOT MODIFY


# 
# i2c_transcever "i2c_transcever" v1.0
#  2022.12.08.19:52:21
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module i2c_transcever
# 
set_module_property DESCRIPTION ""
set_module_property NAME i2c_transcever
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME i2c_transcever
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL i2c_master
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file i2c_master.vhd VHDL PATH components/i2c_master.vhd TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter input_clk INTEGER 50000000
set_parameter_property input_clk DEFAULT_VALUE 50000000
set_parameter_property input_clk DISPLAY_NAME input_clk
set_parameter_property input_clk TYPE INTEGER
set_parameter_property input_clk UNITS None
set_parameter_property input_clk ALLOWED_RANGES -2147483648:2147483647
set_parameter_property input_clk HDL_PARAMETER true
add_parameter bus_clk INTEGER 100000
set_parameter_property bus_clk DEFAULT_VALUE 100000
set_parameter_property bus_clk DISPLAY_NAME bus_clk
set_parameter_property bus_clk TYPE INTEGER
set_parameter_property bus_clk UNITS None
set_parameter_property bus_clk ALLOWED_RANGES -2147483648:2147483647
set_parameter_property bus_clk HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point port
# 
add_interface port conduit end
set_interface_property port associatedClock clock
set_interface_property port associatedReset reset
set_interface_property port ENABLED true
set_interface_property port EXPORT_OF ""
set_interface_property port PORT_NAME_MAP ""
set_interface_property port CMSIS_SVD_VARIABLES ""
set_interface_property port SVD_ADDRESS_GROUP ""

add_interface_port port ena ena Input 1
add_interface_port port addr addr Input 7
add_interface_port port rw rw Input 1
add_interface_port port data_wr data_wr Input 8
add_interface_port port busy busy Output 1
add_interface_port port data_rd data_rd Output 8
add_interface_port port ack_error ack_error Bidir 1


# 
# connection point SCL
# 
add_interface SCL conduit end
set_interface_property SCL associatedClock clock
set_interface_property SCL associatedReset reset
set_interface_property SCL ENABLED true
set_interface_property SCL EXPORT_OF ""
set_interface_property SCL PORT_NAME_MAP ""
set_interface_property SCL CMSIS_SVD_VARIABLES ""
set_interface_property SCL SVD_ADDRESS_GROUP ""

add_interface_port SCL scl_in in Input 1
add_interface_port SCL scl_oe oe Output 1


# 
# connection point SDA
# 
add_interface SDA conduit end
set_interface_property SDA associatedClock clock
set_interface_property SDA associatedReset reset
set_interface_property SDA ENABLED true
set_interface_property SDA EXPORT_OF ""
set_interface_property SDA PORT_NAME_MAP ""
set_interface_property SDA CMSIS_SVD_VARIABLES ""
set_interface_property SDA SVD_ADDRESS_GROUP ""

add_interface_port SDA sda_in in Input 1
add_interface_port SDA sda_oe oe Output 1

